FROM ubuntu:latest

ARG INSTALL_JDK_VERSION \
	INSTALL_ANDROID_SDK_VERSION \
	INSTALL_ANDROID_TOOLS_VERSION \
	INSTALL_NODE_VERSION \
	WORKSPACE \
	JAVA_HOME \
	ANDROID_HOME \
	ANDROID_SDK_ROOT \
	ANDROID_TOOLS \
	CORDOVA_PATH

ENV INSTALL_JDK_VERSION=${INSTALL_JDK_VERSION} \
    INSTALL_ANDROID_SDK_VERSION=${INSTALL_ANDROID_SDK_VERSION} \
    INSTALL_ANDROID_TOOLS_VERSION=${INSTALL_ANDROID_TOOLS_VERSION} \
    INSTALL_NODE_VERSION=${INSTALL_NODE_VERSION} \
    WORKSPACE=${WORKSPACE} \
	JAVA_HOME=${JAVA_HOME} \
    ANDROID_HOME=${ANDROID_HOME} \
    ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT} \
    ANDROID_TOOLS=${ANDROID_TOOLS} \
    CORDOVA_PATH=${CORDOVA_PATH}

COPY scripts/envSetup.sh /

# All setup takes place in the envSetup.sh script in order to only add a single 
# layer to the image, whilst maintaining readability.
RUN chmod +x ./envSetup.sh && \
	. ./envSetup.sh varsAreSet